[[main]]
  identifier = 'home'
  name = 'Home'
  pageref = '/'
  weight = -300

[[main]]
  weight = -289
  #parent = 'classes'
  # weight = 300
  identifier = 'material'
  name = 'Material'
  pageref = '/material'
[[main]]
  identifier = 'debug'
  name = 'Localhost'
  pageref = '/debug'
  weight = -301
  alert = 'primary'

[[main]]
  identifier = 'classes'
  name = 'Classes'
  pageref = '/classes/ss2025'
  weight = -290



[[main]]
  identifier = 'software_projects'
  name = 'Software Projects'
  pageref = '/software_projects'
  weight = -175

[[main]]
  identifier = 'misc'
  name = 'Misc'
  pageref = '/misc'
  weight = -150



[[main]]
  identifier = 'contact'
  name = 'Contact Info'
  pageref = '/contact'
  weight = -140

##
## Classes Submenu
##

[[main]]
  parent = 'classes'
  identifier = '/classes/ss2025/info2'
  name = 'B7 Informatik 2'
  pageref = '/classes/ss2025/info2'
  weight = 10

[[main]]
  parent = 'classes'
  identifier = '/classes/ss2025/wt1'
  name = 'B21 WT1 Verteilte Systeme'
  pageref = '/classes/ss2025/wt1'
  weight = 20

[[main]]
  parent = 'classes'
  identifier = '/classes/ss2025/m1'
  name = 'M1 Media Programming'
  pageref = '/classes/ss2025/m1'
  weight = 30

[[main]]
  parent = 'classes'
  identifier = '/classes/ss2025/buddyprogramm'
  name = 'AWE Buddyprogramm'
  pageref = '/classes/ss2025/buddyprogramm'
  weight = 40

[[main]]
  parent = 'classes'
  identifier = '/classes/ss2025'
  name = 'All SoSe 2025'
  pageref = '/classes/ss2025'
  weight = 50

  ##
  ## Other Submenues
  ##


[[main]]
  identifier = 'studies'
  name = 'Studies'
  pageref = '/studies'
  weight = -170

[[main]]
parent = 'studies'
identifier = '/studies/thesis/'
name = 'Thesis'
pageref = '/studies/thesis'
weight = 10
[[main]]
parent = 'studies'
identifier = '/studies/ic/'
name = 'IC'
pageref = '/studies/ic'
weight = 20
[[main]]
parent = 'studies'
identifier = '/studies/bafoeg/'
name = 'Bafoeg'
pageref = '/studies/bafoeg'
weight = 25
[[main]]
parent = 'studies'
identifier = '/studies/grading/'
name = 'Grading Info'
pageref = '/studies/grading'
weight = 30

