---
language: ruby
rvm:
- 2.3.0
install:
- bundle install
script:
- bundle exec rake test:travis_verbose
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
