name: Prof. Dr. B. Kleinen
encoding: UTF-8
serverencoding: UTF-8
permalink: /news/:title/
markdown: kramdown
highlighter: rouge
breadcrumb_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
baseurl: /
exclude: ['_bin','aliasses.sh','vendor','Rakefile','Gemfile', 'Gemfile.lock', 'link-checker-crawled-pages.pstore','README.md','./_site_htw','_site_htw','/_site_htw/','./_site_htw/','_site_htw/','/_site_htw/']
excerpt_separator: ""
production_url : http://bkleinen.github.io
rss_path : rss.xml
atom_path : atom.xml
title: B. Kleinen
author:
  name: B. Kleinen
  email: kleinen@htw-berlin.de
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: kleinen
      layout: "default"
