
destination: _site_htw
encoding: ISO-8859-1
baseurl: /people/kleinen/

# jekyll build --config _config.yml, _htwconfig.yml
# encoding
# see http://jekyllrb.com/docs/configuration/
# ruby -e 'puts Encoding::list.join("\n")'
