baseURL = 'https://bkleinen.github.io'
languageCode = 'en-us'
title = 'Prof. Dr. Barne Kleinen'
# sectionPagesMenu = "main"
theme = "greenpage"
enableGitInfo = true
disableKinds = ['taxonomy', 'term']
[params]
  serverencoding = "UTF-8"
  generatedLinks = true # set this to false to detect unlinked pages
