[[main]]
  identifier = 'home'
  name = 'Home'
  pageref = '/'
  weight = -300

[[main]]
  weight = -289
  #parent = 'classes'
  # weight = 300
  identifier = 'material'
  name = 'Material'
  pageref = '/material'
[[main]]
  identifier = 'debug'
  name = 'Localhost'
  pageref = '/debug'
  weight = -301
  alert = 'primary'


[[main]]
  identifier = 'classes'
  name = 'Classes'
  pageref = '/classes'
  weight = -290

##
## Classes Submenu
##

[[main]]
  parent = 'classes'
  identifier = '/classes/ss2024/info2'
  name = 'B 1 Informatik 2'
  pageref = '/classes/ss2024/info2'
  weight = 5
[[main]]
  parent = 'classes'
  identifier = '/classes/ss2024/projects'
  name = 'Praxisprojekte'
  pageref = '/classes/ss2024/projects'
  weight = 10
[[main]]
  parent = 'classes'
  identifier = '/classes/ss2024/m1-web'
  name = 'M 1 Mediaprogramming'
  pageref = '/classes/ss2024/m1-web'
  weight = 20
[[main]]
  parent = 'classes'
  identifier = '/classes/ss2024/masterseminar'
  name = 'M 17.1 Masterseminar'
  pageref = '/classes/ss2024/m17-masterseminar'
  weight = 25

[[main]]
  parent = 'classes'
  identifier = '/classes/ss2024'
  name = 'All SoSe 2024'
  pageref = '/classes/ss2024'
  weight = 40
[[main]]
  parent = 'classes'
  identifier = '/classes/'
  name = 'All Classes'
  pageref = '/classes'
  weight = 50

  ##
  ## Other
  ##




[[main]]
  identifier = 'studies'
  name = 'Studies'
  pageref = '/studies'
  weight = -170

[[main]]
parent = 'studies'
identifier = '/studies/thesis/'
name = 'Thesis'
pageref = '/studies/thesis'
weight = 10
[[main]]
parent = 'studies'
identifier = '/studies/ic/'
name = 'IC'
pageref = '/studies/ic'
weight = 20
[[main]]
parent = 'studies'
identifier = '/studies/bafoeg/'
name = 'Bafoeg'
pageref = '/studies/bafoeg'
weight = 25
[[main]]
parent = 'studies'
identifier = '/studies/grading/'
name = 'Grading Info'
pageref = '/studies/grading'
weight = 30


[[main]]
  identifier = 'software_projects'
  name = 'Software Projects'
  pageref = '/software_projects'
  weight = -175

[[main]]
  identifier = 'misc'
  name = 'Misc'
  pageref = '/misc'
  weight = -150



[[main]]
  identifier = 'contact'
  name = 'Contact Info'
  pageref = '/contact'
  weight = -140
